// this file is a tempoary fix.
// Eventually, all these files should be exposing their
// own interface and requesting their own dependencies
// rather than monkey-patching a global

require('aws-sdk/dist/aws-sdk')
window.AWSCognito = window.AWS
require('./CognitoUser')
require('./CognitoUserPool')
require('./CognitoRefreshToken')
require('./CognitoIdToken')
require('./CognitoAccessToken')
require('./AuthenticationDetails')
require('./CognitoUserSession')
require('./CognitoUserAttribute')
require('./AuthenticationHelper')
require('./DateHelper')

module.exports = {
  AWS: window.AWS,
  AWSCognito: window.AWSCognito,
  CognitoUser: window.AWSCognito.CognitoIdentityServiceProvider.CognitoUser,
  CognitoUserPool: window.AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool,
  CognitoRefreshToken: window.AWSCognito.CognitoIdentityServiceProvider.CognitoRefreshToken,
  CognitoIdToken: window.AWSCognito.CognitoIdentityServiceProvider.CognitoIdToken,
  CognitoAccessToken: window.AWSCognito.CognitoIdentityServiceProvider.CognitoAccessToken,
  AuthenticationDetails: window.AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails,
  CognitoUserSession: window.AWSCognito.CognitoIdentityServiceProvider.CognitoUserSession,
  CognitoUserAttribute: window.AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute,
  AuthenticationHelper: window.AWSCognito.CognitoIdentityServiceProvider.AuthenticationHelper,
  DateHelper: window.AWSCognito.CognitoIdentityServiceProvider.DateHelper,
  util: window.AWS.util,
  VERSION: window.AWS.VERSION,
  Signers: window.AWS.Signers,
  Protocol: window.AWS.Protocol,
  XML: window.AWS.XML,
  JSON: window.AWS.JSON,
  Model: window.AWS.Model,
  apiLoader: window.AWS.apiLoader,
  Service: window.AWS.Service,
  Credentials: window.AWS.Credentials,
  CredentialProviderChain: window.AWS.CredentialProviderChain,
  TemporaryCredentials: window.AWS.TemporaryCredentials,
  WebIdentityCredentials: window.AWS.WebIdentityCredentials,
  CognitoIdentityCredentials: window.AWS.CognitoIdentityCredentials,
  SAMLCredentials: window.AWS.SAMLCredentials,
  Config: window.AWS.Config,
  config: window.AWS.config,
  Endpoint: window.AWS.Endpoint,
  HttpRequest: window.AWS.HttpRequest,
  HttpResponse: window.AWS.HttpResponse,
  HttpClient: window.AWS.HttpClient,
  SequentialExecutor: window.AWS.SequentialExecutor,
  EventListeners: window.AWS.EventListeners,
  Request: window.AWS.Request,
  Response: window.AWS.Response,
  ResourceWaiter: window.AWS.ResourceWaiter,
  ParamValidator: window.AWS.ParamValidator,
  events: window.AWS.events,
  XHRClient: window.AWS.XHRClient,
  ACM: window.AWS.ACM,
  APIGateway: window.AWS.APIGateway,
  ApplicationAutoScaling: window.AWS.ApplicationAutoScaling,
  AutoScaling: window.AWS.AutoScaling,
  CloudFormation: window.AWS.CloudFormation,
  CloudFront: window.AWS.CloudFront,
  CloudHSM: window.AWS.CloudHSM,
  CloudTrail: window.AWS.CloudTrail,
  CloudWatch: window.AWS.CloudWatch,
  CloudWatchEvents: window.AWS.CloudWatchEvents,
  CloudWatchLogs: window.AWS.CloudWatchLogs,
  CodeCommit: window.AWS.CodeCommit,
  CodeDeploy: window.AWS.CodeDeploy,
  CodePipeline: window.AWS.CodePipeline,
  CognitoIdentity: window.AWS.CognitoIdentity,
  CognitoIdentityServiceProvider: window.AWS.CognitoIdentityServiceProvider,
  CognitoSync: window.AWS.CognitoSync,
  ConfigService: window.AWS.ConfigService,
  DeviceFarm: window.AWS.DeviceFarm,
  DirectConnect: window.AWS.DirectConnect,
  DynamoDB: window.AWS.DynamoDB,
  DynamoDBStreams: window.AWS.DynamoDBStreams,
  EC2: window.AWS.EC2,
  ECR: window.AWS.ECR,
  ECS: window.AWS.ECS,
  ElastiCache: window.AWS.ElastiCache,
  ElasticBeanstalk: window.AWS.ElasticBeanstalk,
  ElasticTranscoder: window.AWS.ElasticTranscoder,
  ELB: window.AWS.ELB,
  EMR: window.AWS.EMR,
  Firehose: window.AWS.Firehose,
  GameLift: window.AWS.GameLift,
  Inspector: window.AWS.Inspector,
  IotData: window.AWS.IotData,
  Kinesis: window.AWS.Kinesis,
  KMS: window.AWS.KMS,
  Lambda: window.AWS.Lambda,
  MachineLearning: window.AWS.MachineLearning,
  MarketplaceCommerceAnalytics: window.AWS.MarketplaceCommerceAnalytics,
  MobileAnalytics: window.AWS.MobileAnalytics,
  OpsWorks: window.AWS.OpsWorks,
  RDS: window.AWS.RDS,
  Redshift: window.AWS.Redshift,
  Route53: window.AWS.Route53,
  Route53Domains: window.AWS.Route53Domains,
  S3: window.AWS.S3,
  SES: window.AWS.SES,
  SNS: window.AWS.SNS,
  SQS: window.AWS.SQS,
  SSM: window.AWS.SSM,
  StorageGateway: window.AWS.StorageGateway,
  STS: window.AWS.STS,
  WAF: window.AWS.WAF
}
